config/routes.rb
Rails.application.routes.draw do

  get 'map_display/index'

  get 'home/index'

  match "/auth/:provider/callback" =>"sessions#create",via:[:get,:post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via:[:get,:post]
  get "home/fetch_friend_data"

   root to: 'home#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  def self.get_friend_data(friend,location_value, user_id)
    self.where(
            name: friend.name,
            screen_name: friend.screen_name,
            location: friend.location,
            latitude: location_value.first,
            longitude: location_value.second,
            user_id: user_id).find_or_create_by(user_id: user_id, screen_name: friend.screen_name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friends
  def self.create_with_omniauth(auth)
    location = auth["info"]["location"] || ""
    if location.present?
      user_location = Geocoder.coordinates("#{location}")
    else
      user_location = []
      user_location[0] = 41.87194
      user_location[1] = 12.56738
    end
    create! do |user|
      user.provider=auth["provider"]
      user.uid=auth["uid"]
      user.name=auth["info"]["name"] || ""
      user.address=auth["info"]["location"] || ""
      user.avatar=auth["info"]["image"] || ""
      user.oauth_token=auth["credentials"]["token"] || ""
      user.oauth_secret=auth["credentials"]["secret"] || ""
      user.latitude = user_location.first
      user.longitude = user_location.second
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include MapDisplayHelper
  helper_method :current_user
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def fetch_friend_data
    client=Twitter::REST::Client.new do |config|
      config.consumer_key = "6udOb18hbicIWoJOBlZIIEENP"
      config.consumer_secret= "QPYFqYsOA3hPGHRploGXLYHqMfMOEj9ROsxqEaoLx7TXrJiPmV"
      config.access_token= "#{current_user.oauth_token}"
      config.access_token_secret="#{current_user.oauth_secret}"
    end
    @friends = client.friends.to_a
    @friends.each do |f|
      if f.location.present?
        location_value = Geocoder.coordinates("#{f.location}")
        if location_value
          Friend.get_friend_data(f,location_value,current_user.id)
        end
      end
    end
    redirect_to map_display_index_path
  end

end

app/controllers/map_display_controller.rb
class MapDisplayController < ApplicationController
  def index
    @markers=[]
    @friends=current_user.friends
    @friends.each do |f|
      marker_data = get_marker_data(f.screen_name, f.name)
      @markers << [marker_data, f.latitude, f.longitude]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth=request.env["omniauth.auth"]
    user=User.find_by_provider_and_uid(auth["provider"],auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id]=user.id
    redirect_to root_url, :notice=>"Logged in Successfully"
  end
  def destroy
    session[:user_id]=nil
    redirect_to root_url, :notice=>"Logged Out Successfully"
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_display_helper.rb
module MapDisplayHelper
  def get_marker_data(screen_name, name) "<strong>Twit:</strong>#{screen_name}
                                          <br/>
                                          <strong>Name:</strong>Name:#{name}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<div class="row">
  <div class="col-lg-6">
    <h2 id="type-blockquotes"><%= link_to "Fetch My Friend", home_fetch_friend_data_path, :class=>"btn btn-primary" %></h2>
    <h2 id="type-blockquotes"><%= link_to "Mappa", map_display_index_path, :class=>"btn btn-primary" %></h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar-collapse collapse" id="navbar_main">
  <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
        <li>Welcome, <%= current_user.name%> <%=image_tag "#{current_user.avatar}"%> <%= link_to "Sign Out", signout_path%> </li>
    <% else %>
        <li><%= link_to "Sign in with Twitter", "/auth/twitter"%></li>
    <% end %>
  </ul>
</div>
<%= yield %>

</body>
</html>

app/views/map_display/index.html.erb
<h1>MapDisplay#index</h1>
<div id="map" style='width: 1200px; height: 600px;'>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false
&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/
tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'
          type='text/javascript'></script>
  <script>
      var locations = <%=raw @markers %>;
      var map = new google.maps.Map(document.getElementById('map'),
              {
                  zoom: 2,
                  center: new google.maps.LatLng(0, 0),
                  mapTypeId: google.maps.MapTypeId.ROADMAP
              });
      var infowindow = new google.maps.InfoWindow();
      var marker, i;
      for (i = 0; i < locations.length; i++) {
          marker = new google.maps.Marker({
              position: new google.maps.LatLng(locations[i][1],
                      locations[i][2]),
              map: map
          });
          google.maps.event.addListener(marker, 'click',
                  (function(marker, i) {
                      return function() {
                          infowindow.setContent(locations[i][0]);
                          infowindow.open(map, marker);
                      }
                  })(marker, i));
      }
  </script>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>